<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=for, initial-scale=1.0">
    <title>Modifier un article</title>

    <!-- charge les différents scripts -->
    <?php include_once './include/script.php'; ?>

    <!-- charge le fichier css -->
    <link rel="stylesheet" href="./assets/css/style.css">
</head>

<body>
    <div class="container">

        <!--Formulaire de modification de l'article. Les données du formulaire sont encodées en "multipart/form-data", ce qui permet l'envoi de fichiers.-->
        <form action="article_update.php?id=<?php echo $article->id_article; ?>" method="post" enctype="multipart/form-data">

            <!-- le champ 'id' est caché à l'utilisateur mais est bien envoyé lors de la soumision du formulaire -->
            <input type="hidden" name="id" value="<?php echo $article->id_article; ?>" />

            <!-- récupère le contenu de l'article -->
            <label>Titre</label>
            <input class="form-control" value="<?php echo $article->titre; ?>" name="titre" id="titre" placeholder="Ici je place mon titre">
            <br />
            <label>Contenu</label>
            <textarea class="form-control" name="contenu"><?php echo $article->contenu; ?></textarea>
            <br />
            <label>Photo</label>
            <input class="form-control" type="file" name="photo" accept="image/jpeg">
            <br />
            <label>Vidéo</label>
            <input class="form-control" value="<?php echo $article->video; ?>" type="text" name="video">
            <br />
            <label>Auteur</label>

            <!-- récupère la liste des auteurs -->
            <select name="id_auteur" class="form-control">
                <?php foreach ($authorList as $row) { ?>
                    <!--vérifie si l'ID de l'auteur de l'article en cours est égal à l'ID de l'auteur dans la boucle en cours -->
                    <?php if ($article->id_auteur == $row->id_auteur) { ?>
                        <!--Alors on affiche le selected pour sélectionner l'auteur-->
                        <option selected="selected" value="<?php echo $row->id_auteur; ?>"><?php echo $row->nom . ' ' . $row->prenom; ?></option>
                    <?php } else { ?>
                        <!--sinon on affiche l'option mais sans le selected-->
                        <option value="<?php echo $row->id_auteur; ?>"><?php echo $row->nom . ' ' . $row->prenom; ?></option>
                    <?php } ?>
                <?php } ?>
            </select>
            <br />

            <!-- récupère les catégories -->
            <?php foreach ($categoryList as $row) { 
                $string = '';
                // coche celles qui sont déjà sélectionnées
                if(in_array($row->id_categorie, $tabIdCategoryArticle)){
                    $string = 'checked';
                }
                ?>
                <input <?php echo $string; ?> type="checkbox" name="category[]" value="<?php echo $row->id_categorie; ?>"> <?php echo $row->nom; ?><br>

            <?php } ?>

            <div class="div mt-3">
                <input type="submit" value="Modifier">
            </div>
            
        </form>
    </div>

    <!-- charge le pied de page -->
    <?php include_once './include/footer.php'; ?>   

</body>

</html>