<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <?php include_once './include/script.php';?>
</head>
<body>

    <h1>
        <?php echo $article->titre; ?>
        (<?php echo date_format(date_create($article->date_publication), 'd/m/Y H:i:s'); ?>)
    </h1> 
    <p>
        <?php foreach($category as $row){?> <?php echo $row->nom; ?>&nbsp;
        <?php }?>
    </p>
    <p><?php echo $article->contenu; ?></p>
    <p>
        <?php echo $article->nom;?> <?php echo $article->prenom;?>
    </p>
    <p>
        <img src="<?php echo $article->image; ?>" >
    </p>
    <p>
    <iframe width="560" height="315" src="<?php echo $article->video; ?>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    </p>    
</body>
</html>