<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=for, initial-scale=1.0">
    <title>Nouvelle recette</title>

    <!-- charge les différents scripts -->
    <?php include_once './include/script.php'; ?>

    <!-- charge le fichier css -->
    <link rel="stylesheet" href="./assets/css/style.css">

</head>

<body>

    <main>
        <?php include_once './include/menu.php'; ?>        

        <div class="container mt-20">
            <br>

            <h1 class="mt-50">Une nouvelle recette</h1>


            <!-- formulaire de rédaction -->
            <form action="article_new.php" method="post" enctype="multipart/form-data">

                <label>Titre</label>
                <input class="form-control" name="titre" id="titre" placeholder="ici je place mon titre"><br>

                <label>Contenu</label>
                <textarea class="form-control" name="contenu"></textarea><br>

                <label>Photo</label>
                <input class="form-control" type="file" name="photo" accept="image/jpeg"><br>

                <label>Video</label>
                <input class="form-control" type="text" name="video"><br>

                <label>Auteur</label>
                <select class="form-control" name="id_auteur">
                    <!-- récupère la liste des auteurs -->
                    <?php foreach ($authorList as $row) { ?>
                        <option value="<?php echo $row->id_auteur; ?>"> <?php echo $row->nom . ' ' . $row->prenom ?></option>
                    <?php } ?>
                </select>
                <br>

                <!-- récupère la liste des catégories -->
                <?php foreach ($categoryList as $row) { ?>
                    <input type="checkbox" name="category[]" value="<?php echo $row->id_categorie; ?>"> <?php echo $row->nom; ?><br>
                <?php } ?>                
                
                <!-- bouton d'envoi -->
                <div class="div mt-3">
                    <input class="form-control btn btn-success mt-10" type="submit" value="Envoyer">
                </div>
            </form>

        </div>

    </main>

    <!-- charge le pied de page -->
    <?php include_once './include/footer.php'; ?>   
</body>

</html>

