<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Accueil</title>
    
    <!-- charge les différents scripts -->
    <?php include_once './include/script.php'; ?>

    <!-- charge le fichier css -->
    <link rel="stylesheet" href="./assets/css/style.css">
</head>

<body>

    <!-- chargement de la barre de navigation et du header avec un article en focus -->
    <?php include_once './include/menu.php'; ?>
    <?php include_once './include/header.php'; ?>

    <main>

        <!-- récupération des différentes catégories avec une boucle  -->
        <?php foreach ($categories as $row) {
            $articleCategory = $articleModel->getArticleByCategoryId($row->id_categorie);
            
        ?>

        <section id="article">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="row"> 

                            <!-- récupère le nom de la catégorie                            -->
                            <h2><?php echo $row->nom; ?></h2>     

                        </div>
                        <div class="row mb-4">
                            <?php 

                                // Ajoute un compteur
                                $counter = 0; 

                                // A chaque 3ème article, fermez la ligne et ouvrez une nouvelle ligne
                                foreach ($articleCategory as $rowCategory) { 
                                    if ($counter % 3 == 0 && $counter > 0) { 
                                    echo '</div><div class="row mb-4">';
                                    }
                            ?>

                            <!-- affiche 3 articles par ligne -->
                            <div class="col-4"> 
                                <div class="card shadow h-100">
                                    <div class="card-image row">

                                        <!-- récupère l'image de l'article -->
                                        <img src="<?php echo $rowCategory->image; ?>" class="h-70 w-80 object-fit-cover img-fluid"  alt="image de la recette">
                                    </div>

                                    <div class="card-body">
                                        <!-- récupère le titre de l'article qui renvoit vers l'article détaillé -->
                                        <h3 class="card-title">
                                            <a href="article_details.php?id=<?php echo $rowCategory->id_article; ?>">
                                                <?php echo htmlspecialchars($rowCategory->titre, ENT_QUOTES, 'UTF-8'); ?>
                                            </a>
                                            
                                        </h3>
            
                                        <!-- Affiche seulement les 200 premiers mots de l'article -->
                                        <p class="card-text">                                            
                                            <?php
                                                // Récupère tous les mots sous forme de tableau                 
                                                $words = str_word_count($rowCategory->contenu, 1);
                                                // Récupère les 200 premiers mots  
                                                $first_200_words = array_slice($words, 0, 200);
                                                // Convertit le tableau en chaîne de caractères  
                                                $text = htmlspecialchars(implode(' ', $first_200_words), ENT_QUOTES, 'UTF-8');
                                                // ajoute '...' à la fin du texte 
                                                $text.= '...';
                                                echo $text;

                                            ?>                                            
                                        </p>

                                        <!-- Lien vers la page détaillée de l'article -->
                                        <a href="article_details.php?id=<?php echo $rowCategory->id_article; ?>">Voir plus</a>  

                                    </div>

                                    <div class="card-footer">
                                        <ul class="list-unstyled d-flex">

                                            <!-- indique la date de publication de l'article -->
                                            <li class="me-2"><small class="text-primary"><?php echo $rowCategory->date_publication; ?></small></li>
                                            
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <?php 
                                $counter++; // Incrémentez le compteur après chaque article
                                } 
                            ?>
                        </div>
                    </div>
                </div>
            </div>


        </section>

        <?php } ?>

    </main>
   
            

</body>

    
</html>

