<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inscription</title>

    <!-- charge les différents scripts -->
    <?php include_once './include/script.php'; ?>

    <!-- charge le fichier css -->
    <link rel="stylesheet" href="../assets/css/style.css">

</head>

<body>

<?php include_once './include/menu.php';?>
<br><br><br>

<div class="container">
    <h1>Inscription</h1>
    <form action="register.php" method="post">
        <label for="">Nom</label>
        <input type="text" name="nom" class="form-control">
        <label for="">Prénom</label>
        <input type="text" name="prenom" class="form-control">
        <label for="">Email</label>
        <input type="text" name="email" class="form-control">
        <label for="">Mot de passe</label>
        <input type="password" name="password" class="form-control">
        <label for="">Merci de resaisir à nouveau votre mot de passe</label>
        <input type="password" name="password2" class="form-control">

        <div class="div mt-3">
            <input type="submit" value="S'inscrire">
        </div>
   </form>
</div>

<!-- charge le pied de page -->
<?php include_once './include/footer.php'; ?>   
    
</body>
</html>